### ISSUE TITLE
missing romi-back-castor.stl in romipi_description/meshes/wheels/

### ISSUE THREAD

**Issue by archie1983** [ftPeter/RomiPi#5]
romi-back-castor.stl file seems to be missing in romipi_description/meshes/wheels/. When I try to bring it up, I get this error: 

[ERROR] [1642774881.506015757]: Could not load resource [package://romipi_description/meshes/wheels/romi-back-castor.stl]: Unable to open file "package://romipi_description/meshes/wheels/romi-back-castor.stl".

Please add the missing file.

**Comment by ftPeter** [comment]
Hi,

I added the file, but I'm concerned it's from a different version of the
model. I currently don't have a working test setup, can you let me know if
this works and makes sense?

Thanks,
Peter

**Comment by archie1983** [comment]
Hey, thanks for that.

Ok, I did find a romi_castor.stl inside src/romipi_description/meshes/bases/. After renaming it and putting it in the wheels directory, the error is gone and it kind of shows up in the model, only shifted to a side- not quite where it is supposed to be, but still on the chassis. So I've been making do with that for a few days now.
![caster_from_chassis_directory](https://user-images.githubusercontent.com/39572467/150803037-203102fd-2a78-482c-849a-59ce6c0055cc.png)

The new STL however- the one that you just added- shows up huge. I need to zoom out so far that the robot is not even visible anymore, just the caster.
![huge_caster](https://user-images.githubusercontent.com/39572467/150803118-757fa410-9752-456c-af89-8c45becce49d.png)

Please see images attached.

Other than that- thanks for the effort. I'm still going through it one project at a time to understand fully, but this is awesome. I ordered a LiDAR and raspberry Pi today to put it all together on my RoMI and hopefully get it all to work. Thanks!

**Comment by ftPeter** [comment]
Hi Arturs,

Thanks for letting me know. I've updated the git repo to reflect that file
being in the wrong folder.

If you want to dig into it, the romipi_description/urdf/romipi.urdf.xacro
is where the offset is configured. If you fiddle with those values, you can
probably get it to line up.

You may have noticed that the model sometimes "bounces." I'm not really
sure why this is happening and I'd be interested to hear back from you if
you see anything.

I'm sorry to not be able to provide more support right now. The new
semester is starting and I don't have as much time to devote to this as I
ordinarily would. I'm really glad to see someone interested though.

Thanks,
Peter
